services:
  disable-internet-via-fritzbox:
    build: .
    container_name: disable-internet-via-fritzbox
    ports:
      - "8080:8000"
    environment:
      - FRITZBOX_USER=${FRITZBOX_USER}
      - FRITZBOX_PASSWORD=${FRITZBOX_PASSWORD}
      - FRITZBOX_IP=${FRITZBOX_IP:-192.168.178.1}
      - FRITZBOX_PORT=${FRITZBOX_PORT:-49000}
      - TARGET_IP=${TARGET_IP:-192.168.178.50}
      - TZ=${TZ:-Europe/Berlin}
    restart: unless-stopped
