version: '3.8'

services:
  disable-internet-via-fritzbox:
    build: .
    container_name: disable-internet-via-fritzbox
    ports:
      - "8080:80"  # Map container's port 80 to host port 8080
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./cgi-bin:/app/cgi-bin:ro
    environment:
      - FRITZBOX_USER=${FRITZBOX_USER}
      - FRITZBOX_PASSWORD=${FRITZBOX_PASSWORD}
      - TARGET_IP=${TARGET_IP:-192.168.178.50}
      - FRITZBOX_IP=${FRITZBOX_IP:-192.168.178.1}
      - FRITZBOX_PORT=${FRITZBOX_PORT:-49000}
      - TZ=${TZ:-Europe/Berlin}
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
    restart: unless-stopped